# Generated by Django 4.2.5 on 2023-09-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_liqueur', to='core.liqueursize'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_liqueur', to='core.liqueursize'),
        ),
    ]
