# Generated by Django 4.2.5 on 2023-09-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_price_alter_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='liqueur_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.liqueursize'),
        ),
    ]
