# Generated by Django 4.2.5 on 2023-09-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_price_remove_item_size_item_liqueur_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='liqueur_size',
            new_name='size',
        ),
    ]
